### ISSUE TITLE
Watch history no longer synced between different computers

### ISSUE THREAD

**Issue by neonshadow** [CodeNinjaUK/youtube-subs-grid#79]
Before the latest update the watch history was synced between different computers (where I am logged into Chrome sync). Now when I go to another computer videos I have already marked as watched are not marked. I hope this makes sense, this is a pretty significant functionality downgrade if intentional, hopefully it's just a bug.

**Comment by DanSmith70** [comment]
Have both devices updated to the latest version of the extension (1.18)? The format for storing history changed with the most recent updated but it needs both devices on the same version to work.

**Comment by neonshadow** [comment]
It is possible that they are not in sync since there was another update. I will double check when I get home tonight. Thanks.

**Comment by neonshadow** [comment]
After several more times going back and forth (and making sure they are all running the same version) I can say it is definitely not working, the history is not synced as it used to be.

**Comment by DanSmith70** [comment]
Damn. Sorry about this! To diagnose this I need to see what's in the developer console. Can you please open the developer console by pressing Ctrl+Shift+J (Windows / Linux) or Cmd+Opt+J (Mac). You then need to visit the the subscription page, and then mark a video as watched. Can you let me know if you get a bunch of red lines (errors) and if so screenshot or paste them here? 

Thanks!

**Comment by neonshadow** [comment]
Nothing seems to happen after I click watched on a video, no errors or anything. However when I load the page there are some seemingly unrelated errors, this is what I get:

`common.js:437 GET https://googleads.g.doubleclick.net/pagead/id net::ERR_BLOCKED_BY_CLIENTsda @ common.js:437g.J @ common.js:441(anonymous function) @ common.js:889g.fm @ common.js:322dfa @ common.js:888g.qu @ common.js:894YB.init @ common.js:2493x @ scheduler.js:15r.F @ scheduler.js:16
1.jpg:1 GET https://i.ytimg.com/i/gURzIxwRJA_MyBK1sr6HHQ/1.jpg 404 ()
common.js:981 GET chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js net::ERR_FAILEDGfa @ common.js:981Nv @ common.js:982(anonymous function) @ common.js:982c.onerror @ common.js:980
common.js:981 GET chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js net::ERR_FAILEDGfa @ common.js:981Nv @ common.js:982(anonymous function) @ common.js:982c.onerror @ common.js:980
common.js:983 GET chrome-extension://fjhoaacokmgbjemoflkofnenfaiekifl/cast_sender.js net::ERR_FAILEDMv @ common.js:983Nv @ common.js:982(anonymous function) @ common.js:982
Resource interpreted as Document but transferred with MIME type text/javascript: "https://s.ytimg.com/yts/jsbin/player-en_US-vflEHWF5a/base.js".`

**Comment by DanSmith70** [comment]
Yeah thats just what ever adblocker you use doing it's thing - not related as you say. Is it still working locally? Like, you can mark something watched, refresh, and it stays watched but it just doesn't transfer to the other device?

**Comment by neonshadow** [comment]
That's correct, it works great locally, it just doesn't transfer over. When I get to the other machine the videos are not marked as watched.

**Comment by DanSmith70** [comment]
Very odd.. just to confirm you're signed in to Chrome on both machines with the same Google account? Also, can you confirm extension syncing is enabled? You can check in Settings > Advanced sync settings

![image](https://cloud.githubusercontent.com/assets/417574/14191856/0c2de3b2-f792-11e5-8333-80fe37dffde0.png)

**Comment by neonshadow** [comment]
Yes I checked that as well to be sure, it's set to Sync everything on both machines as in the screenshot you posted.

**Comment by DanSmith70** [comment]
Well, right now I'm officially confused. The thing is, the way Chrome stores synced data it either works or it doesn't - if it saves at all (which it is or it wouldn't work locally) it should sync and Chrome handles all that behind the scenes.

Let me have a think about this..

**Comment by neonshadow** [comment]
Ok, for now I have just reverted to 1.16. It doesn't sync but it does fix the issue of auto-loading older and older videos forever. Seems more stable in general as well. There is significant delay before the controls start working when you load the page now.

**Comment by DanSmith70** [comment]
1.16 should be syncing as well - is it not? Also is the delay there for you on 1.16? I've been trying to track down whats causing that delay but as far as I can tell its something YT did around the same time I released the extension because the delay is there for me with all extensions off..

**Comment by neonshadow** [comment]
Ok I have been using the latest version for a while now and I think I see what the issue is. Basically videos that you actually watch, that is you open the video and view it, are synced. However videos that you simply click the "mark as watched" button but don't open the video are not synced. I hope that helps to track this one down.

**Comment by DanSmith70** [comment]
Can you let me know if this issue is fixed for you now? There was a permissions error that may have cause this to be working for some and not others.

**Comment by neonshadow** [comment]
After using it for a few days going back and forth just to be sure, I can say... it's not fixed :( It's honestly not a huge deal, as it's fast enough to just click the watched button on them again. Probably YouTube broke something.
